version: "3"
services:
  jaw-postgres:
    image: postgres:12.10
    network_mode: bridge
    container_name: jaw-postgres
    volumes:
      - jaw-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  jaw-redis:
    image: redis:6.2-alpine
    network_mode: bridge
    container_name: jaw-redis
    volumes:
      - jaw-data:/var/lib/redis/data
    expose:
      - 6379
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redisadmin

  jaw-platform:
    image: jaw-platform:latest
    network_mode: bridge
    container_name: jaw-platform
    build: .
    env_file:
      - .env
    expose:
      - 8880
    ports:
      - 8880:8880
    depends_on:
      - jaw-postgres
      - jaw-redis
    links:
      - jaw-postgres
      - jaw-redis

volumes:
  jaw-data:
