// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTennants holds the string denoting the tennants edge name in mutations.
	EdgeTennants = "tennants"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// TennantsTable is the table that holds the tennants relation/edge.
	TennantsTable = "tennants"
	// TennantsInverseTable is the table name for the Tennant entity.
	// It exists in this package in order to avoid circular dependency with the "tennant" package.
	TennantsInverseTable = "tennants"
	// TennantsColumn is the table column denoting the tennants relation/edge.
	TennantsColumn = "account_id"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
