// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DBConnection struct {
	Host     string `json:"host"`
	User     string `json:"user"`
	Password string `json:"password"`
	Dbname   string `json:"dbname"`
	Port     int    `json:"port"`
	Sslmode  string `json:"sslmode"`
}

type FlatTable struct {
	Name    string    `json:"name"`
	Columns []*Column `json:"columns"`
}

type ReportClause struct {
	Selections []*ReportSelection `json:"selections"`
}

type ReportData struct {
	Rows []map[string]interface{} `json:"rows"`
}

type Column struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type ReportSelection struct {
	ID       string `json:"_id"`
	Field    string `json:"field"`
	Operator string `json:"operator"`
	Value    string `json:"value"`
}
