// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DBConnection struct {
	Host     string `json:"host"`
	User     string `json:"user"`
	Password string `json:"password"`
	Dbname   string `json:"dbname"`
	Port     int    `json:"port"`
	Sslmode  string `json:"sslmode"`
}
