// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// TennantsColumns holds the columns for the "tennants" table.
	TennantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "external_id", Type: field.TypeString},
		{Name: "cloud", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeUUID},
	}
	// TennantsTable holds the schema information for the "tennants" table.
	TennantsTable = &schema.Table{
		Name:       "tennants",
		Columns:    TennantsColumns,
		PrimaryKey: []*schema.Column{TennantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tennants_accounts_tennants",
				Columns:    []*schema.Column{TennantsColumns[4]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		TennantsTable,
	}
)

func init() {
	TennantsTable.ForeignKeys[0].RefTable = AccountsTable
}
