// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (a *Account) Tennants(ctx context.Context) (result []*Tennant, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = a.NamedTennants(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = a.Edges.TennantsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = a.QueryTennants().All(ctx)
	}
	return result, err
}

func (t *Tennant) Account(ctx context.Context) (*Account, error) {
	result, err := t.Edges.AccountOrErr()
	if IsNotLoaded(err) {
		result, err = t.QueryAccount().Only(ctx)
	}
	return result, err
}
