// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Report is the predicate function for report builders.
type Report func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
